import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "./dashboard/_components/Navbar";

// Use Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // adjust weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body 
        suppressHydrationWarning={true}
        className={`${poppins.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider 
            attribute="class"
            defaultTheme="system"
          >
            <Navbar/>
            {children}
             <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}